#!/bin/sh
projectName=$1
mkdir $projectName
mkdir $projectName/bin
mkdir $projectName/src
mkdir $projectName/src/include
mkdir $projectName/tests
mkdir $projectName/tests/include
################################################################################
echo Create the makefile
cd $projectName
echo  "CC=gcc" > makefile
echo  "test:" >> makefile
echo  "\t@\$(CC) -g -lrt -lm -o bin/test$projectName tests/test$projectName.c src/library.c -I." >> makefile
echo  "\t@bin/test$projectName" >> makefile
echo  "build:" >> makefile
echo  "\t@\$(CC) -g -lrt -lm -o bin/$projectName src/$projectName.c src/library.c -I." >> makefile
echo  "all:" >> makefile
echo  "\t@\$(CC) -g -lrt -lm -o bin/$projectName src/$projectName.c src/library.c -I." >> makefile
echo  "\t@\$(CC) -g -lrt -lm -o bin/test$projectName tests/test$projectName.c src/library.c -I." >> makefile
echo  "cov:" >> makefile		
echo  "\t@\$(CC) -g -lrt -lm -Wall -fprofile-arcs -ftest-coverage -o bin/test$projectName tests/test$projectName.c src/library.c -I." >> makefile
echo  "\tlcov --directory . --zerocounters" >> makefile
echo  "\t@bin/test$projectName" >> makefile
echo  "\tgcov test$projectName" >> makefile
echo  "\tgcov library" >> makefile
echo  "\tlcov --directory . --capture --output-file coverage/app.info" >> makefile
echo  "\tgenhtml coverage/app.info -o ./coverage" >> makefile
echo  "travistest:" >> makefile
echo  "\t\$(CC) -g -lrt -lm -Wall -fprofile-arcs -ftest-coverage -o test$projectName tests/test$projectName.c src/library.c -I." >> makefile
echo  "\t./test$projectName" >> makefile
echo  "\tgcov test$projectName" >> makefile
echo  "\tgcov library" >> makefile
echo  "travisbuild:" >> makefile
echo  "\t\$(CC) -g -lrt -lm -Wall -fprofile-arcs -ftest-coverage -o $projectName src/$projectName.c src/library.c -I." >> makefile
echo  "\t./$projectName" >> makefile
echo  "\tgcov $projectName" >> makefile

################################################################################
echo Create the main source file
cd src
cat > $projectName.c <<-EOF
/*
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/

#include <stdio.h>
#include "include/library.h"

int main(int argc, char **argv)
{
    printf("Hello World\n");
}
EOF

################################################################################
echo Create the library file
#cd $projectName/src
cat > library.c <<-EOF
/*
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/

#include "include/library.h"
int MEMORY_ALLOCATION_COUNTER = 0;
int NULL_DEALLOCATION_COUNTER = 0;

///
/// Wrapper for malloc() to keep count of the number of memory allocations to
/// help tracking memory leaks.
///
void *allocate(size_t size)
{
    void *p = malloc(size);
    if (p == NULL) {
        perror("Unable to allocate buffer");
        exit(1);
    }
    MEMORY_ALLOCATION_COUNTER++;
    return p;
}

///
/// Wrapper for calloc() to keep count of the number of memory allocations to
/// help tracking memory leaks.
///
void *allocate_clear(size_t nmemb, size_t size)
{
    void *p = calloc(nmemb, size);
    if (p == NULL) {
        perror("Unable to allocate buffer");
        exit(1);
    }
    MEMORY_ALLOCATION_COUNTER++;
    return p;
}

///
/// Wrapper for free() to keep count of the number of memory deallocations to 
/// help tracking memory leaks. Also counts attempts to deallocate on NULL pointers.
///
void deallocate(void *ptr)
{
    if (!ptr) {
        NULL_DEALLOCATION_COUNTER++;
        return;
    }
    MEMORY_ALLOCATION_COUNTER--;
    free(ptr);
}
EOF

################################################################################
echo Create the library header file
cd include
cat > library.h <<-EOF
/*
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdbool.h>
#include <assert.h>
#include <stdarg.h>
//
// Version macros for compile-time API detection
//
#define MED_VERSION_MAJOR   1
#define MED_VERSION_MINOR   0
#define MED_VERSION_PATCH   0
#define MED_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define MED_VERSION \
    MED_MAKE_VERSION(MED_VERSION_MAJOR, \
    MED_VERSION_MINOR, \
    MED_VERSION_PATCH)
//
// Wrappers for malloc(), calloc() and free()
//
void* allocate(size_t size);
void* allocate_clear(size_t nmemb, size_t size);
void deallocate(void *ptr);
extern int MEMORY_ALLOCATION_COUNTER;
extern int NULL_DEALLOCATION_COUNTER;    
EOF

################################################################################
echo Create the main test source file
cd ../../tests
cat > test$projectName.c <<- EOF
/*
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/

#include "include/minunit.h"
#include "../src/include/library.h"

void test_setup(void) {
	/* Nothing */
}

void test_teardown(void) {
	/* Nothing */
}

MU_TEST(test_fail) {
	mu_fail("Hello World!");
}

MU_TEST_SUITE(test_suite) {
	MU_SUITE_CONFIGURE(&test_setup, &test_teardown);

	MU_RUN_TEST(test_fail);
}

int main(int argc, char **argv)
{
    MU_RUN_SUITE(test_suite);
    MU_REPORT();
    
    if (MEMORY_ALLOCATION_COUNTER != 0 || NULL_DEALLOCATION_COUNTER != 0) {
        printf
            ("\033[0;31m----------------------------------------------\n");
        printf("Net Memory Allocations    = %i\n",
               MEMORY_ALLOCATION_COUNTER);
        printf("NULL Memory Deallocations = %i\n",
               NULL_DEALLOCATION_COUNTER);
        printf
            ("----------------------------------------------\033[0m\n\n");
    }
        
    return 0;    
}
EOF

################################################################################
echo Create minunit unit test header file
cd include
curl https://raw.githubusercontent.com/MichaelStedman/HelloWorldC/master/tests/include/minunit.h > minunit.h

